### ISSUE TITLE
Critical error on startup

### ISSUE THREAD

**Issue by NathanBnm** [padjis/ghistory#3] opened 2020-02-16 11:55 UTC
When double-clicking to a bash entry to copy it the following assertion is fired:
```
(com.github.padjis.ghistory:6362): Gtk-CRITICAL **: 12:53:28.427: gtk_entry_get_text: assertion 'GTK_IS_ENTRY (entry)' failed
```

**Comment by padjis** [comment] 2020-04-14 15:21
I could not reproduce the bug, would you like to try it out again? Otherwise, I will close the issue

**Comment by NathanBnm** [comment] 2020-04-14 15:52
@padjis installing from source and running from terminal is creating this critical error above. I thought it was when double-clicking but it seems it occurs at startup.

But double-clicking on en entry still makes the app crash.

**Comment by padjis** [comment] 2020-05-01 15:57
Oh I think you don't get how the application works, the idea is that when double clicking on an entry, the content gets copied on the clipboard and the application shutdown. Exactly like clipboard managers, do we agree that this is not an issue then? I mean working a bit on the critical error can be done, but it works as intended anyway

**Comment by NathanBnm** [comment] 2020-05-01 17:32
> Oh I think you don't get how the application works, the idea is that when double clicking on an entry, the content gets copied on the clipboard and the application shutdown. Exactly like clipboard managers, do we agree that this is not an issue then? I mean working a bit on the critical error can be done, but it works as intended anyway

Well I wasn't expecting that. When the user don't know that the app will close it looks like the app just crashed. But I understand now. There is still a need to fix this critical error.

**Closed as completed** 2020-05-09 16:11 UTC
